# Generated by Django 3.2.9 on 2021-11-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
