# Generated by Django 3.2.9 on 2021-11-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_auto_20211104_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='lang',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian'), ('en', 'English')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('MATH', 'Math'), ('ENGLISH', 'English')], max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('HARD', 'Hard'), ('MEDIUM', 'Medium'), ('EASY', 'Easy')], max_length=100),
        ),
    ]
