# Generated by Django 3.2.9 on 2021-11-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_questionoptions_quiz_quizoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('hard', 'Hard'), ('medium', 'Medium'), ('easy', 'Easy')], max_length=50),
        ),
    ]
