# Generated by Django 3.2.9 on 2021-11-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_auto_20211107_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizoptions',
            name='before_id',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('BIOLOGY', 'Biology')], max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(choices=[('MATH', 'Math'), ('ENGLISH', 'English'), ('BIOLOGY', 'Biology')], max_length=50),
        ),
    ]
