# Generated by Django 3.2.9 on 2021-11-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploads',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='updated_by',
        ),
    ]
